include:
  - proxy.yaml

services:
  web:
    #build:
    #context: .
    #dockerfile: Dockerfile.python
    image: cr.yandex/crpgrtsua4sv7p0spldk/fastapi-app:hello
    networks:
      backend:
        ipv4_address: 172.20.0.5
    restart: always

    environment:
      - DB_HOST=db
      - DB_USER=${MYSQL_USER}
      - DB_PASSWORD=${MYSQL_PASSWORD}
      - DB_NAME=${MYSQL_DATABASE}
      - DB_TABLE=${DB_TABLE:-requests}
    depends_on:
      - db

  db:
    image: mysql:8
    networks:
      backend:
        ipv4_address: 172.20.0.10
    restart: always

    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
